# Generated by Django 2.0.2 on 2018-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20180409_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
