# Generated by Django 2.0.2 on 2018-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20180409_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
