# Generated by Django 2.0.2 on 2018-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20180410_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
