# Generated by Django 2.0.2 on 2018-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_auto_20180411_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='colour',
            new_name='color',
        ),
    ]
