# Generated by Django 2.0.2 on 2018-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_auto_20180411_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='requester',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
