# Generated by Django 2.0.2 on 2018-04-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_auto_20180418_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='itadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.Itadmin'),
        ),
    ]
